[project]
name = "reward-feedback-pointing-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "klibs",
    "pyfirmata>=1.1.0",
]

[tool.uv.sources]
klibs = { git = "https://github.com/a-hurst/klibs" }
